all: true
testonly: false
with-expecter: true
dir: tests/mocks/{{ replaceAll .InterfaceDirRelative "pkg" ""}}
outpkg: '{{.PackageName}}_mocks'
filename: '{{.InterfaceName | snakecase }}_mock.go'
packages:
  hex/phoenix/config:
    config:
      recursive: true
  hex/phoenix/handlers:
    config:
      recursive: true
